server:
  port: 8080

  error:
    include-message: always

spring:
  datasource:
    password: pass
    url: jdbc:postgresql://localhost:5432/customer
    username: catalin
  jpa:
    hibernate:
      ddl-auto: create-drop
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
          use_sql-comments: true
          generate_statistic: true

      show-sql: true

  main:
    web-application-type: servlet

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: TRACE